# Setup and configure ruby things for reddit app
  - name: Install ruby and rubygems and required packages
    apt: "name={{ item }} state=present"
    with_items:
      - ruby-full
      - ruby-dev
      - build-essential
    tags: ruby

  - name: Install Ruby bundler
    gem:
      name: bundler
      state: present
      user_install: no
    tags: ruby
