- name: Configure App
  hosts: app
  become: true
  roles:
    - app
    - role: nginx
      nginx_sites:
        custom_bar:
          template: custom_bar.conf.j2
          server_name: _
          upstream_name: reddit
          server_upstream: 127.0.0.1:9292
          listen_port: 80
